name: "setup-sqlite-version"
description: "Set up a specific version of SQLite, for testing and ebugging"
author: "Alex Garcia"
inputs:
  version:
    description: "The SQLite version you wish to install."
    required: true
  cflags:
    description: "CFLAGS to use when compiling SQLite. Can be used to pass in SQLite compile time options."
    required: false
outputs:
  sqlite-location:
    description: TODO
runs:
  using: "node16"
  main: "dist/index.js"
