name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-linux:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asg017/sqlite-versions@main
        id: sqlite-versions
        with:
          version: "3.39.0"
      - run: ls
      - run: python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
      - run: |
          if [ "$(python3 -c 'import sqlite3; print(sqlite3.sqlite_version)')" != "3.39.0" ]; then
            echo "version mismatch"
            exit 1
          fi
